# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import iot2050_system_firmware_pb2 as iot2050__system__firmware__pb2


class SystemFirmwareStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCapabilities = channel.unary_unary(
                '/iot2050.systemfirmware.SystemFirmware/GetCapabilities',
                request_serializer=iot2050__system__firmware__pb2.Empty.SerializeToString,
                response_deserializer=iot2050__system__firmware__pb2.CapabilitiesReply.FromString,
                )
        self.Inspect = channel.unary_unary(
                '/iot2050.systemfirmware.SystemFirmware/Inspect',
                request_serializer=iot2050__system__firmware__pb2.InspectRequest.SerializeToString,
                response_deserializer=iot2050__system__firmware__pb2.InspectionReply.FromString,
                )
        self.Update = channel.unary_unary(
                '/iot2050.systemfirmware.SystemFirmware/Update',
                request_serializer=iot2050__system__firmware__pb2.UpdateRequest.SerializeToString,
                response_deserializer=iot2050__system__firmware__pb2.OperationReply.FromString,
                )
        self.StartUpdate = channel.unary_unary(
                '/iot2050.systemfirmware.SystemFirmware/StartUpdate',
                request_serializer=iot2050__system__firmware__pb2.UpdateRequest.SerializeToString,
                response_deserializer=iot2050__system__firmware__pb2.OperationReply.FromString,
                )
        self.GetOperation = channel.unary_unary(
                '/iot2050.systemfirmware.SystemFirmware/GetOperation',
                request_serializer=iot2050__system__firmware__pb2.OperationRequest.SerializeToString,
                response_deserializer=iot2050__system__firmware__pb2.OperationReply.FromString,
                )
        self.InspectRollback = channel.unary_unary(
                '/iot2050.systemfirmware.SystemFirmware/InspectRollback',
                request_serializer=iot2050__system__firmware__pb2.RollbackRequest.SerializeToString,
                response_deserializer=iot2050__system__firmware__pb2.RollbackReply.FromString,
                )
        self.Rollback = channel.unary_unary(
                '/iot2050.systemfirmware.SystemFirmware/Rollback',
                request_serializer=iot2050__system__firmware__pb2.RollbackRequest.SerializeToString,
                response_deserializer=iot2050__system__firmware__pb2.OperationReply.FromString,
                )
        self.StartRollback = channel.unary_unary(
                '/iot2050.systemfirmware.SystemFirmware/StartRollback',
                request_serializer=iot2050__system__firmware__pb2.RollbackRequest.SerializeToString,
                response_deserializer=iot2050__system__firmware__pb2.OperationReply.FromString,
                )


class SystemFirmwareServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCapabilities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Inspect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOperation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InspectRollback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rollback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartRollback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SystemFirmwareServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCapabilities,
                    request_deserializer=iot2050__system__firmware__pb2.Empty.FromString,
                    response_serializer=iot2050__system__firmware__pb2.CapabilitiesReply.SerializeToString,
            ),
            'Inspect': grpc.unary_unary_rpc_method_handler(
                    servicer.Inspect,
                    request_deserializer=iot2050__system__firmware__pb2.InspectRequest.FromString,
                    response_serializer=iot2050__system__firmware__pb2.InspectionReply.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=iot2050__system__firmware__pb2.UpdateRequest.FromString,
                    response_serializer=iot2050__system__firmware__pb2.OperationReply.SerializeToString,
            ),
            'StartUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.StartUpdate,
                    request_deserializer=iot2050__system__firmware__pb2.UpdateRequest.FromString,
                    response_serializer=iot2050__system__firmware__pb2.OperationReply.SerializeToString,
            ),
            'GetOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOperation,
                    request_deserializer=iot2050__system__firmware__pb2.OperationRequest.FromString,
                    response_serializer=iot2050__system__firmware__pb2.OperationReply.SerializeToString,
            ),
            'InspectRollback': grpc.unary_unary_rpc_method_handler(
                    servicer.InspectRollback,
                    request_deserializer=iot2050__system__firmware__pb2.RollbackRequest.FromString,
                    response_serializer=iot2050__system__firmware__pb2.RollbackReply.SerializeToString,
            ),
            'Rollback': grpc.unary_unary_rpc_method_handler(
                    servicer.Rollback,
                    request_deserializer=iot2050__system__firmware__pb2.RollbackRequest.FromString,
                    response_serializer=iot2050__system__firmware__pb2.OperationReply.SerializeToString,
            ),
            'StartRollback': grpc.unary_unary_rpc_method_handler(
                    servicer.StartRollback,
                    request_deserializer=iot2050__system__firmware__pb2.RollbackRequest.FromString,
                    response_serializer=iot2050__system__firmware__pb2.OperationReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'iot2050.systemfirmware.SystemFirmware', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SystemFirmware(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/iot2050.systemfirmware.SystemFirmware/GetCapabilities',
            iot2050__system__firmware__pb2.Empty.SerializeToString,
            iot2050__system__firmware__pb2.CapabilitiesReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Inspect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/iot2050.systemfirmware.SystemFirmware/Inspect',
            iot2050__system__firmware__pb2.InspectRequest.SerializeToString,
            iot2050__system__firmware__pb2.InspectionReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/iot2050.systemfirmware.SystemFirmware/Update',
            iot2050__system__firmware__pb2.UpdateRequest.SerializeToString,
            iot2050__system__firmware__pb2.OperationReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/iot2050.systemfirmware.SystemFirmware/StartUpdate',
            iot2050__system__firmware__pb2.UpdateRequest.SerializeToString,
            iot2050__system__firmware__pb2.OperationReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/iot2050.systemfirmware.SystemFirmware/GetOperation',
            iot2050__system__firmware__pb2.OperationRequest.SerializeToString,
            iot2050__system__firmware__pb2.OperationReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InspectRollback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/iot2050.systemfirmware.SystemFirmware/InspectRollback',
            iot2050__system__firmware__pb2.RollbackRequest.SerializeToString,
            iot2050__system__firmware__pb2.RollbackReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Rollback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/iot2050.systemfirmware.SystemFirmware/Rollback',
            iot2050__system__firmware__pb2.RollbackRequest.SerializeToString,
            iot2050__system__firmware__pb2.OperationReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartRollback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/iot2050.systemfirmware.SystemFirmware/StartRollback',
            iot2050__system__firmware__pb2.RollbackRequest.SerializeToString,
            iot2050__system__firmware__pb2.OperationReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
