# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import iot2050_firmware_pb2 as iot2050__firmware__pb2


class FirmwareStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCapabilities = channel.unary_unary(
                '/iot2050.firmware.Firmware/GetCapabilities',
                request_serializer=iot2050__firmware__pb2.Empty.SerializeToString,
                response_deserializer=iot2050__firmware__pb2.CapabilitiesReply.FromString,
                )
        self.Inspect = channel.unary_unary(
                '/iot2050.firmware.Firmware/Inspect',
                request_serializer=iot2050__firmware__pb2.InspectRequest.SerializeToString,
                response_deserializer=iot2050__firmware__pb2.InspectionReply.FromString,
                )
        self.Update = channel.unary_unary(
                '/iot2050.firmware.Firmware/Update',
                request_serializer=iot2050__firmware__pb2.UpdateRequest.SerializeToString,
                response_deserializer=iot2050__firmware__pb2.OperationReply.FromString,
                )
        self.GetOperation = channel.unary_unary(
                '/iot2050.firmware.Firmware/GetOperation',
                request_serializer=iot2050__firmware__pb2.OperationRequest.SerializeToString,
                response_deserializer=iot2050__firmware__pb2.OperationReply.FromString,
                )
        self.StreamOperationLogs = channel.unary_stream(
                '/iot2050.firmware.Firmware/StreamOperationLogs',
                request_serializer=iot2050__firmware__pb2.StreamOperationLogsRequest.SerializeToString,
                response_deserializer=iot2050__firmware__pb2.OperationLog.FromString,
                )
        self.InspectRollback = channel.unary_unary(
                '/iot2050.firmware.Firmware/InspectRollback',
                request_serializer=iot2050__firmware__pb2.RollbackRequest.SerializeToString,
                response_deserializer=iot2050__firmware__pb2.RollbackReply.FromString,
                )
        self.Rollback = channel.unary_unary(
                '/iot2050.firmware.Firmware/Rollback',
                request_serializer=iot2050__firmware__pb2.RollbackRequest.SerializeToString,
                response_deserializer=iot2050__firmware__pb2.OperationReply.FromString,
                )


class FirmwareServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCapabilities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Inspect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOperation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamOperationLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InspectRollback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rollback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FirmwareServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCapabilities,
                    request_deserializer=iot2050__firmware__pb2.Empty.FromString,
                    response_serializer=iot2050__firmware__pb2.CapabilitiesReply.SerializeToString,
            ),
            'Inspect': grpc.unary_unary_rpc_method_handler(
                    servicer.Inspect,
                    request_deserializer=iot2050__firmware__pb2.InspectRequest.FromString,
                    response_serializer=iot2050__firmware__pb2.InspectionReply.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=iot2050__firmware__pb2.UpdateRequest.FromString,
                    response_serializer=iot2050__firmware__pb2.OperationReply.SerializeToString,
            ),
            'GetOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOperation,
                    request_deserializer=iot2050__firmware__pb2.OperationRequest.FromString,
                    response_serializer=iot2050__firmware__pb2.OperationReply.SerializeToString,
            ),
            'StreamOperationLogs': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamOperationLogs,
                    request_deserializer=iot2050__firmware__pb2.StreamOperationLogsRequest.FromString,
                    response_serializer=iot2050__firmware__pb2.OperationLog.SerializeToString,
            ),
            'InspectRollback': grpc.unary_unary_rpc_method_handler(
                    servicer.InspectRollback,
                    request_deserializer=iot2050__firmware__pb2.RollbackRequest.FromString,
                    response_serializer=iot2050__firmware__pb2.RollbackReply.SerializeToString,
            ),
            'Rollback': grpc.unary_unary_rpc_method_handler(
                    servicer.Rollback,
                    request_deserializer=iot2050__firmware__pb2.RollbackRequest.FromString,
                    response_serializer=iot2050__firmware__pb2.OperationReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'iot2050.firmware.Firmware', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Firmware(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/iot2050.firmware.Firmware/GetCapabilities',
            iot2050__firmware__pb2.Empty.SerializeToString,
            iot2050__firmware__pb2.CapabilitiesReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Inspect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/iot2050.firmware.Firmware/Inspect',
            iot2050__firmware__pb2.InspectRequest.SerializeToString,
            iot2050__firmware__pb2.InspectionReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/iot2050.firmware.Firmware/Update',
            iot2050__firmware__pb2.UpdateRequest.SerializeToString,
            iot2050__firmware__pb2.OperationReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/iot2050.firmware.Firmware/GetOperation',
            iot2050__firmware__pb2.OperationRequest.SerializeToString,
            iot2050__firmware__pb2.OperationReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamOperationLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/iot2050.firmware.Firmware/StreamOperationLogs',
            iot2050__firmware__pb2.StreamOperationLogsRequest.SerializeToString,
            iot2050__firmware__pb2.OperationLog.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InspectRollback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/iot2050.firmware.Firmware/InspectRollback',
            iot2050__firmware__pb2.RollbackRequest.SerializeToString,
            iot2050__firmware__pb2.RollbackReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Rollback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/iot2050.firmware.Firmware/Rollback',
            iot2050__firmware__pb2.RollbackRequest.SerializeToString,
            iot2050__firmware__pb2.OperationReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
