# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from gRPC import iot2050_firmware_pb2 as gRPC_dot_iot2050__firmware__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class FirmwareStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Inspect = channel.unary_unary(
                '/iot2050.firmware.Firmware/Inspect',
                request_serializer=gRPC_dot_iot2050__firmware__pb2.InspectRequest.SerializeToString,
                response_deserializer=gRPC_dot_iot2050__firmware__pb2.InspectReply.FromString,
                )
        self.Update = channel.unary_unary(
                '/iot2050.firmware.Firmware/Update',
                request_serializer=gRPC_dot_iot2050__firmware__pb2.UpdateRequest.SerializeToString,
                response_deserializer=gRPC_dot_iot2050__firmware__pb2.UpdateReply.FromString,
                )
        self.GetStatus = channel.unary_unary(
                '/iot2050.firmware.Firmware/GetStatus',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=gRPC_dot_iot2050__firmware__pb2.GetStatusReply.FromString,
                )
        self.WatchLogs = channel.unary_stream(
                '/iot2050.firmware.Firmware/WatchLogs',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=gRPC_dot_iot2050__firmware__pb2.WatchLogsReply.FromString,
                )
        self.Rollback = channel.unary_unary(
                '/iot2050.firmware.Firmware/Rollback',
                request_serializer=gRPC_dot_iot2050__firmware__pb2.RollbackRequest.SerializeToString,
                response_deserializer=gRPC_dot_iot2050__firmware__pb2.RollbackReply.FromString,
                )


class FirmwareServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Inspect(self, request, context):
        """Inspect a package or validate the service-owned rollback artifact.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Start a package-based or raw firmware update.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Read the current durable operation state.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchLogs(self, request, context):
        """Stream best-effort live messages; messages are not replayed.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rollback(self, request, context):
        """Start a rollback from the service-owned backup artifact.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FirmwareServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Inspect': grpc.unary_unary_rpc_method_handler(
                    servicer.Inspect,
                    request_deserializer=gRPC_dot_iot2050__firmware__pb2.InspectRequest.FromString,
                    response_serializer=gRPC_dot_iot2050__firmware__pb2.InspectReply.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=gRPC_dot_iot2050__firmware__pb2.UpdateRequest.FromString,
                    response_serializer=gRPC_dot_iot2050__firmware__pb2.UpdateReply.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=gRPC_dot_iot2050__firmware__pb2.GetStatusReply.SerializeToString,
            ),
            'WatchLogs': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchLogs,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=gRPC_dot_iot2050__firmware__pb2.WatchLogsReply.SerializeToString,
            ),
            'Rollback': grpc.unary_unary_rpc_method_handler(
                    servicer.Rollback,
                    request_deserializer=gRPC_dot_iot2050__firmware__pb2.RollbackRequest.FromString,
                    response_serializer=gRPC_dot_iot2050__firmware__pb2.RollbackReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'iot2050.firmware.Firmware', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Firmware(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Inspect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/iot2050.firmware.Firmware/Inspect',
            gRPC_dot_iot2050__firmware__pb2.InspectRequest.SerializeToString,
            gRPC_dot_iot2050__firmware__pb2.InspectReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/iot2050.firmware.Firmware/Update',
            gRPC_dot_iot2050__firmware__pb2.UpdateRequest.SerializeToString,
            gRPC_dot_iot2050__firmware__pb2.UpdateReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/iot2050.firmware.Firmware/GetStatus',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            gRPC_dot_iot2050__firmware__pb2.GetStatusReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WatchLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/iot2050.firmware.Firmware/WatchLogs',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            gRPC_dot_iot2050__firmware__pb2.WatchLogsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Rollback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/iot2050.firmware.Firmware/Rollback',
            gRPC_dot_iot2050__firmware__pb2.RollbackRequest.SerializeToString,
            gRPC_dot_iot2050__firmware__pb2.RollbackReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
