# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gRPC/EIOManager/iot2050-eio.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!gRPC/EIOManager/iot2050-eio.proto\x12\neiomanager\"\"\n\rDeployRequest\x12\x11\n\tyaml_data\x18\x01 \x01(\t\".\n\x0b\x44\x65ployReply\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1f\n\x0fRetrieveRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"C\n\rRetrieveReply\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\tyaml_data\x18\x03 \x01(\t\"-\n\x0fSyncTimeRequest\x12\x11\n\x04time\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_time\"0\n\rSyncTimeReply\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"9\n\x15UpdateFirmwareRequest\x12\x0e\n\x06\x65ntity\x18\x01 \x01(\x05\x12\x10\n\x08\x66irmware\x18\x02 \x01(\x0c\"6\n\x13UpdateFirmwareReply\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"!\n\x0f\x43heckFWURequest\x12\x0e\n\x06\x65ntity\x18\x01 \x01(\x05\"0\n\rCheckFWUReply\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x15\n\x13ReadEIOEventRequest\"C\n\x11ReadEIOEventReply\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\r\n\x05\x65vent\x18\x03 \x01(\t2\xc8\x03\n\nEIOManager\x12>\n\x06\x44\x65ploy\x12\x19.eiomanager.DeployRequest\x1a\x17.eiomanager.DeployReply\"\x00\x12\x44\n\x08Retrieve\x12\x1b.eiomanager.RetrieveRequest\x1a\x19.eiomanager.RetrieveReply\"\x00\x12\x44\n\x08SyncTime\x12\x1b.eiomanager.SyncTimeRequest\x1a\x19.eiomanager.SyncTimeReply\"\x00\x12V\n\x0eUpdateFirmware\x12!.eiomanager.UpdateFirmwareRequest\x1a\x1f.eiomanager.UpdateFirmwareReply\"\x00\x12\x44\n\x08\x43heckFWU\x12\x1b.eiomanager.CheckFWURequest\x1a\x19.eiomanager.CheckFWUReply\"\x00\x12P\n\x0cReadEIOEvent\x12\x1f.eiomanager.ReadEIOEventRequest\x1a\x1d.eiomanager.ReadEIOEventReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gRPC.EIOManager.iot2050_eio_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DEPLOYREQUEST']._serialized_start=49
  _globals['_DEPLOYREQUEST']._serialized_end=83
  _globals['_DEPLOYREPLY']._serialized_start=85
  _globals['_DEPLOYREPLY']._serialized_end=131
  _globals['_RETRIEVEREQUEST']._serialized_start=133
  _globals['_RETRIEVEREQUEST']._serialized_end=164
  _globals['_RETRIEVEREPLY']._serialized_start=166
  _globals['_RETRIEVEREPLY']._serialized_end=233
  _globals['_SYNCTIMEREQUEST']._serialized_start=235
  _globals['_SYNCTIMEREQUEST']._serialized_end=280
  _globals['_SYNCTIMEREPLY']._serialized_start=282
  _globals['_SYNCTIMEREPLY']._serialized_end=330
  _globals['_UPDATEFIRMWAREREQUEST']._serialized_start=332
  _globals['_UPDATEFIRMWAREREQUEST']._serialized_end=389
  _globals['_UPDATEFIRMWAREREPLY']._serialized_start=391
  _globals['_UPDATEFIRMWAREREPLY']._serialized_end=445
  _globals['_CHECKFWUREQUEST']._serialized_start=447
  _globals['_CHECKFWUREQUEST']._serialized_end=480
  _globals['_CHECKFWUREPLY']._serialized_start=482
  _globals['_CHECKFWUREPLY']._serialized_end=530
  _globals['_READEIOEVENTREQUEST']._serialized_start=532
  _globals['_READEIOEVENTREQUEST']._serialized_end=553
  _globals['_READEIOEVENTREPLY']._serialized_start=555
  _globals['_READEIOEVENTREPLY']._serialized_end=622
  _globals['_EIOMANAGER']._serialized_start=625
  _globals['_EIOMANAGER']._serialized_end=1081
# @@protoc_insertion_point(module_scope)
