#!/bin/sh

### BEGIN INIT INFO
# Provides:	        status-led
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	System status LED indicator
### END INIT INFO

set -e

case "$1" in
    start)
        echo timer > /sys/class/leds/status-led-green/trigger
	;;
    stop)
        echo gpio > /sys/class/leds/status-led-green/trigger
        echo 0 > /sys/class/leds/status-led-green/inverted
	;;
    force-reload|restart)
        echo gpio > /sys/class/leds/status-led-green/trigger
        echo 0 > /sys/class/leds/status-led-green/inverted
	;;
    *)
	    echo "Usage: $0 {start|stop|restart|force-reload}" 1>&2
	    exit 1
	;;
esac

exit 0
