# OpenSSL config file for using the External Signer provider
config_diagnostics = 1
openssl_conf = openssl_init

[openssl_init]
providers = provider_sect

[provider_sect]
default = default_sect
legacy = legacy_sect
extsign_provider = extsign_provider_sect

[default_sect]
activate = 1

[legacy_sect]
activate = 1

[extsign_provider_sect]
activate = 1

# extsign-specific configuration
identity = extsign_provider
module = extsign_provider.so
SCHEME = extsign
CLIENT_COMMAND = "/usr/share/trust-center-remote-signer/runsignclient.sh"
CLIENT_HASHFILE = /var/spool/trust-center-remote-signer/in/hash
CLIENT_SIGNATUREFILE = /var/spool/trust-center-remote-signer/out/hash
SIGNER_CERTIFICATE = /usr/share/trust-center-credential/trust-center-mpk.crt
