# Copyright (c) Siemens AG, 2023
#
# SPDX-License-Identifier: MIT
#
# This is an example config file for IOT2050-SM signal modules to demonstrate
# how to config the external signal modules via YAML config file
#
slot1:
  description: |
    SM1223-AC/RLY (8-channel digital input and 8-channel output module)

    Configuration Items:

    0. MLFB

      Must be "6ES7223-1QH32-0XB0"

    1. Digital inputs

      - di.ch0_3_delay_time:
          Input delay time of di channel 0 ~ channel 3

          value options:
            - 2: 0.2 msec
            - 3: 0.4 msec
            - 4: 0.8 msec
            - 5: 1.6 msec
            - 6: 3.2 msec
            - 7: 6.4 msec
            - 9: 12.8 msec

      - di.ch4_7_delay_time:
          input delay time of di channel 4 ~ channel 7

          value options: same as di.ch0_3_delay_time

    2. Digital outputs

      - dq.behavior_with_OD:
        All dq channels behavior with OD

        value options:
          - 2: hold last value
          - 3: use substitute

      - dq.ch[0-7]:

        - substitute:
            Substitute value for the channel

            value options:
              - 0: use 0 as the substitute value for this channel
              - 1: use 1 as the substitute value for this channel

  mlfb: "6ES7223-1QH32-0XB0"

  di:
    ch0_3_delay_time: 9
    ch4_7_delay_time: 9

  dq:
    behavior_with_OD: 3
    ch0:
      substitute: 0
    ch1:
      substitute: 0
    ch2:
      substitute: 0
    ch3:
      substitute: 0
    ch4:
      substitute: 0
    ch5:
      substitute: 0
    ch6:
      substitute: 0
    ch7:
      substitute: 0

slot2:
  description: |
    SM1231-AI (8-channel analog measurement module for measuring current or voltage)

    Configuration Items:

    0. MLFB

      Must be "6ES7231-4HF32-0XB0"

    1. Per module configuration

      - power_alarm:
          user power alarm of all channels

          value options:
            - true: enabled
            - false: disabled

      - integ_time:
          integration time

          value options:
            - 0: 400 Hz
            - 1: 60 Hz
            - 2: 50 Hz
            - 3: 10 Hz

    2. Per channel configuration

      - ch[0-7].type:
          measurement type

          value options:
            - 1: voltage
            - 3: 2 wire current

      - ch[0-7].range:
          measurement range

          value options:
            - 2: 0 - 20ma
            - 3: 4 - 20ma
            - 7: +/- 2.5v
            - 8: +/- 5v
            - 9: +/- 10v

      - ch[0-7].smooth:
          smoothing

          value options:
            - 0: 1X rejection period
            - 1: 4X rejection period
            - 2: 16X rejection period
            - 3: 32X rejection period

      - ch[0-7].open_wire_alarm:
          open wire alarm

          value options:
            - true: enabled
            - false: disabled

      - ch[0-7].overflow_alarm:
          overflow alarm

          value options:
            - true: enabled
            - false: disabled

      - ch[0-7].underflow_alarm:
          underflow alarm

          value options:
            - true: enabled
            - false: disabled

  mlfb: "6ES7231-4HF32-0XB0"

  power_alarm: true

  integ_time: 2

  ch0:
    type: 1
    range: 9
    smooth: 1
    open_wire_alarm: false
    overflow_alarm: true
    underflow_alarm: true

  ch1:
    type: 1
    range: 9
    smooth: 1
    open_wire_alarm: false
    overflow_alarm: true
    underflow_alarm: true

  ch2:
    type: 1
    range: 9
    smooth: 1
    open_wire_alarm: false
    overflow_alarm: true
    underflow_alarm: true

  ch3:
    type: 1
    range: 9
    smooth: 1
    open_wire_alarm: false
    overflow_alarm: true
    underflow_alarm: true

  ch4:
    type: 1
    range: 9
    smooth: 1
    open_wire_alarm: false
    overflow_alarm: true
    underflow_alarm: true

  ch5:
    type: 1
    range: 9
    smooth: 1
    open_wire_alarm: false
    overflow_alarm: true
    underflow_alarm: true

  ch6:
    type: 1
    range: 9
    smooth: 1
    open_wire_alarm: false
    overflow_alarm: true
    underflow_alarm: true

  ch7:
    type: 1
    range: 9
    smooth: 1
    open_wire_alarm: false
    overflow_alarm: true
    underflow_alarm: true

slot3:
  description: No module for this slot
  mlfb: "NA"

slot4:
  description: No module for this slot
  mlfb: "NA"

slot5:
  description: No module for this slot
  mlfb: "NA"

slot6:
  description: No module for this slot
  mlfb: "NA"
