#!/usr/bin/env python3
#
# Copyright (c) Siemens AG, 2026
#
# SPDX-License-Identifier: MIT

import sys

from iot2050_firmware_update import main


if __name__ == '__main__':
    sys.exit(main(sys.argv))
