env:
  browser: true
  es2021: true
  node: true
extends:
  - standard
  - plugin:react/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {
  semi: [2, "always"]
}
